### ISSUE TITLE
Achieve the co-embedding of speech-image

### ISSUE THREAD

**Issue by tarudesu** [jasonppy/word-discovery#2]
Hi, I'm working for finding the pseudo-semantic pairs between speech and its corresponding image. Actually, I tried to achieve the `coarse_cross_relationship_score_matrix` from the _trainer.py_. However, I'm not sure that what should I do to obtain that kind of pairs. (I get the features of image and audio by VG-HuBERT_3 by **_trm_** and **_audio_encoder_**, respectively)

Is your model able to do that? If possible, how can I know where is the pairs in the co-embedding?

(I tried to cut a part of audio (exactly, a word) to try find something like its corresponding "segmentation" on the image)

Could you help me for this, please? Thank you in advance!

**Comment by tarudesu** [comment]
@jasonppy could you please help me for this kind of question?

**Comment by jasonppy** [comment]
Hi Taru,

Sorry for the late reply. this line calculate the matrix https://github.com/jasonppy/word-discovery/blob/master/steps/trainer.py#L61

it's using the audio_cls and visual_out['visual_cls'] from this line: https://github.com/jasonppy/word-discovery/blob/master/models/dual_encoder.py#L131

Let me know if you have further questions.

**Comment by tarudesu** [comment]
Oh, thank you for that. Actually, I got that kind of matrix. But, is it possible to know something like the pseudo-semantic pairs (image-speech)? (Eg: <image: a dog and a cat> <speech: there is a dog and a cat ...> => pseudo-semantic pairs would be like: <image:dog>:<speech:dog>,... 

Moreover, if i can know exactly this pairs, could I get the position of the image-segmentations of that pairs? (Eg: where is the "dog" in the image)?

**Comment by jasonppy** [comment]
No sure I understand what you mean by pseudo-semantic pairs

about image segmentation. That's an interesting research question to which I don't have an answer yet. Looking forward to your findings.
