### ISSUE TITLE
Issue on downloading SpokenCOCO dataset

### ISSUE THREAD

**Issue by cayl-crypto** [jasonppy/word-discovery#5]
We are trying to download the SpokenCOCO dataset from the link "https://data.csail.mit.edu/placesaudio/SpokenCOCO.tar.gz". We both tried downloading from the browser and command line. When we try downloading from the browser downloading canceled at 1.1 GB of data but it continues partially as we retry downloading. Similarly, in the command line the download is stopped at 1.1GB of data without throwing an error. We are using the torchvision download_url function for this. What may cause the issue? or is there any other way to download this dataset?

**Comment by jasonppy** [comment]
Thanks for the heads up. This dataset is hosted by MIT CSAIL so we don't have control on it, could you contact [Jim Glass](https://www.csail.mit.edu/person/jim-glass) or [Andrew Rouditchenko](https://people.csail.mit.edu/roudi/)?

**Comment by cayl-crypto** [comment]
wget --tries=inf https://data.csail.mit.edu/placesaudio/SpokenCOCO.tar.gz -P ${coco_root} # 64G

adding --tries=inf resolved the issue.
