### ISSUE TITLE
Environment error

### ISSUE THREAD

**Issue by kilcimurat** [jasonppy/word-discovery#6]
*My Ubuntu version is Ubuntu 20.04.6 LTS
*When I try to install the libraries with conda 
conda install -c conda-forge torch==1.10.0 apex=0.1 fairseq==0.10.0 faiss==1.5.3 matplotlib==3.5.1 numpy==1.20.3 Pillow==9.1.1 scikit-learn==1.1.1 scipy==1.6.3 seaborn==0.11.1 SoundFile==0.10.3.post1 torchvision==0.9.0 tqdm==4.60.0
Channels
 - conda-forge
 - defaults
Platform: linux-64
Collecting package metadata (repodata.json): done
Solving environment: failed

PackagesNotFoundError: The following packages are not available from current channels:

  - apex=0.1*
  - fairseq==0.10.0
  - faiss==1.5.3
  - soundfile==0.10.3.post1
  - torch==1.10.0

Current channels:

  - https://conda.anaconda.org/conda-forge
  - defaults

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.

*When I try to install the libraries in requirement.txt into Conda Environment with pip, I get this error.
pip install -r requirements.txt 
ERROR: Could not find a version that satisfies the requirement apex==0.1 (from versions: 0.9.8dev.linux-i686, 0.9.8.dev0, 0.9.8a0.dev0, 0.9.9.9.dev0, 0.9.10.dev0)
ERROR: No matching distribution found for apex==0.1
especially apex and faiss libraries cannot be installed with pip and then fairseq and torch libraries are incompatible.

We're encountering issues while trying to install libraries from a requirements.txt file in a Conda Environment using pip, specifically with apex, faiss, fairseq, and torch libraries. The installation fails due to compatibility issues and unavailability of certain versions. When we attempt to install these libraries with conda, I face a PackagesNotFoundError for versions specified in my command. Using higher versions of these libraries leads to training issues such as 'loss nan' and gradient overload. I need assistance in resolving these installation and compatibility problems to complete my training setup successfully.

**Comment by jasonppy** [comment]
Sorry to hear the installation is not smooth.

Please install pytorch 1.10.0 first, following instruction in https://pytorch.org/get-started/previous-versions/#v1100

Then install apex following https://github.com/NVIDIA/apex?tab=readme-ov-file#linux

then install faiss with `conda install -c conda-forge faiss-gpu` (you don't need to install faiss if you don't intend to run kmeans clustering 

then fairseq with pip install fairseq==0.10.0

**Comment by kilcimurat** [comment]
Thank you, this is how I was able to set it up and start training.
